data = [
    {'name': 'Cristiano Ronaldo', 'follower count': 600_000_000, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Lionel Messi', 'follower count': 485_000_000, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Selena Gomez', 'follower count': 430_000_000, 'description': 'Singer/Actress', 'country': 'USA'},
    {'name': 'Dwayne Johnson', 'follower count': 395_000_000, 'description': 'Actor/Wrestler', 'country': 'USA'},
    {'name': 'Kylie Jenner', 'follower count': 400_000_000, 'description': 'Businesswoman/Model', 'country': 'USA'},
    {'name': 'Kim Kardashian', 'follower count': 370_000_000, 'description': 'TV Personality/Businesswoman', 'country': 'USA'},
    {'name': 'Ariana Grande', 'follower count': 380_000_000, 'description': 'Singer/Actress', 'country': 'USA'},
    {'name': 'Beyoncé', 'follower count': 320_000_000, 'description': 'Singer/Actress', 'country': 'USA'},
    {'name': 'Justin Bieber', 'follower count': 290_000_000, 'description': 'Singer', 'country': 'Canada'},
    {'name': 'Taylor Swift', 'follower count': 275_000_000, 'description': 'Singer/Songwriter', 'country': 'USA'},
    {'name': 'Neymar Jr.', 'follower count': 220_000_000, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Virat Kohli', 'follower count': 260_000_000, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Khloé Kardashian', 'follower count': 310_000_000, 'description': 'TV Personality/Businesswoman', 'country': 'USA'},
    {'name': 'Kendall Jenner', 'follower count': 300_000_000, 'description': 'Model/TV Personality', 'country': 'USA'},
    {'name': 'Billie Eilish', 'follower count': 110_000_000, 'description': 'Singer/Songwriter', 'country': 'USA'},
    {'name': 'Shawn Mendes', 'follower count': 70_000_000, 'description': 'Singer/Songwriter', 'country': 'Canada'},
    {'name': 'Zendaya', 'follower count': 185_000_000, 'description': 'Actress', 'country': 'USA'},
    {'name': 'Jennifer Lopez', 'follower count': 250_000_000, 'description': 'Singer/Actress', 'country': 'USA'},
    {'name': 'Priyanka Chopra', 'follower count': 90_000_000, 'description': 'Actress', 'country': 'India'},
    {'name': 'LeBron James', 'follower count': 170_000_000, 'description': 'Basketball Player', 'country': 'USA'},
    {'name': 'Robert Downey Jr.', 'follower count': 60_000_000, 'description': 'Actor', 'country': 'USA'},
    {'name': 'Will Smith', 'follower count': 65_000_000, 'description': 'Actor/Rapper', 'country': 'USA'},
    {'name': 'Emma Watson', 'follower count': 75_000_000, 'description': 'Actress', 'country': 'UK'},
    {'name': 'Chris Hemsworth', 'follower count': 60_000_000, 'description': 'Actor', 'country': 'Australia'},
]
